//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoardFarm.Data {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoardFarm.Data.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 and 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_And {
            get {
                return ResourceManager.GetString("ConfigWindow_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable statistic gathering 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_DisableStatisticGathering {
            get {
                return ResourceManager.GetString("ConfigWindow_DisableStatisticGathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disables global gathering of runtimes and found hoards.
        ///Purely used to build a accurate global statistic.
        ///Only sends time of a run, if a hoard is found and the travel time to hoard.
        ///Character, timestamp or any other identifying info will NEVER send! 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_DisableStatisticGathering_Help {
            get {
                return ResourceManager.GetString("ConfigWindow_DisableStatisticGathering_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Actually no really much to configure here. 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_GreetingText {
            get {
                return ResourceManager.GetString("ConfigWindow_GreetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language: 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_Language {
            get {
                return ResourceManager.GetString("ConfigWindow_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 German 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_Language_de {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client-Language 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_Language_default {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_Language_en {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 French 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_Language_fr {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Japanese 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_Language_ja {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Korean 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_Language_ko {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chinese 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_Language_zh {
            get {
                return ResourceManager.GetString("ConfigWindow_Language_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show &quot;Open Hoardfarm&quot;-Overlay 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_OpenHoardfarmOverlay {
            get {
                return ResourceManager.GetString("ConfigWindow_OpenHoardfarmOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset local statistics 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_ResetStatistics {
            get {
                return ResourceManager.GetString("ConfigWindow_ResetStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 %d seconds 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_Seconds {
            get {
                return ResourceManager.GetString("ConfigWindow_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slower mode 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_SlowMode {
            get {
                return ResourceManager.GetString("ConfigWindow_SlowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Slow mode will wait some seconds before requeue again.
        ///Not really necessary, but makes some people feel better. 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_SlowMode_Help {
            get {
                return ResourceManager.GetString("ConfigWindow_SlowMode_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support on Ko-fi 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_SupportKofi {
            get {
                return ResourceManager.GetString("ConfigWindow_SupportKofi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wanna support me? Buy me a coffee! 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_SupportMe {
            get {
                return ResourceManager.GetString("ConfigWindow_SupportMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HoardFarm Config 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_Title {
            get {
                return ResourceManager.GetString("ConfigWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wait between: 的本地化字符串。
        /// </summary>
        internal static string ConfigWindow_WaitBetween {
            get {
                return ResourceManager.GetString("ConfigWindow_WaitBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Hoardfarm 的本地化字符串。
        /// </summary>
        internal static string DeepDungeonMenuOverlay_OpenHoardfarm {
            get {
                return ResourceManager.GetString("DeepDungeonMenuOverlay_OpenHoardfarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opens the Hoard Farm window.
        ////hoardfarm config | c → Open the config window.
        ////hoardfarm enable | e → Enable farming mode.
        ////hoardfarm disable | d → Disable farming mode.
        ////hoardfarm toggle | t → Toggle farming mode.
        /// 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_CommandHelp {
            get {
                return ResourceManager.GetString("HoardFarm_CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_Done {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entering HoH 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_EnteringHoH {
            get {
                return ResourceManager.GetString("HoardFarm_Status_EnteringHoH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_Error {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please prepare before starting.
        ///You need at least one Intuition Pomander
        ///and one Concealment. 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_Error_MinimalSetup {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Error_MinimalSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please prepare before starting.
        ///Floor One is not supported. 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_Error_Unprepared {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Error_Unprepared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_Finished {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hoard Found 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_HoardFound {
            get {
                return ResourceManager.GetString("HoardFarm_Status_HoardFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Leaving 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_Leaving {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Leaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move to Hoard 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_MoveToHoard {
            get {
                return ResourceManager.GetString("HoardFarm_Status_MoveToHoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Moving to HoH 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_MoveToHoH {
            get {
                return ResourceManager.GetString("HoardFarm_Status_MoveToHoH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Hoard 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_NoHoard {
            get {
                return ResourceManager.GetString("HoardFarm_Status_NoHoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Player died 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_PlayerDied {
            get {
                return ResourceManager.GetString("HoardFarm_Status_PlayerDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retainer Running 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_RetainerRunning {
            get {
                return ResourceManager.GetString("HoardFarm_Status_RetainerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_Running {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_Searching {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Searching {0} 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_SearchingObject {
            get {
                return ResourceManager.GetString("HoardFarm_Status_SearchingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_Timeout {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unreachable 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_Unreachable {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_Waiting {
            get {
                return ResourceManager.GetString("HoardFarm_Status_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for vnavmesh 的本地化字符串。
        /// </summary>
        internal static string HoardFarm_Status_WaitingNavmesh {
            get {
                return ResourceManager.GetString("HoardFarm_Status_WaitingNavmesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do retainers: 的本地化字符串。
        /// </summary>
        internal static string MainWindow_DoRetainers {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If ALL Retainer are done 的本地化字符串。
        /// </summary>
        internal static string MainWindow_DoRetainers_AllDone {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers_AllDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If ANY Retainer is done 的本地化字符串。
        /// </summary>
        internal static string MainWindow_DoRetainers_AnyDone {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers_AnyDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This features requires AutoRetainer to be installed and configured. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_DoRetainers_AutoretainerNeeded {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers_AutoretainerNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ports to Limsa Lominsa and runs retainers between runs if done. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_DoRetainers_Port {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check the current world name or Inventory slot. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_DoRetainers_WrongWorld {
            get {
                return ResourceManager.GetString("MainWindow_DoRetainers_WrongWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable HoardFarm Mode 的本地化字符串。
        /// </summary>
        internal static string MainWindow_EnableHoardFarmMode {
            get {
                return ResourceManager.GetString("MainWindow_EnableHoardFarmMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Farm Mode: 的本地化字符串。
        /// </summary>
        internal static string MainWindow_FarmMode {
            get {
                return ResourceManager.GetString("MainWindow_FarmMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Efficiency 的本地化字符串。
        /// </summary>
        internal static string MainWindow_FarmMode_Efficiency {
            get {
                return ResourceManager.GetString("MainWindow_FarmMode_Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Efficiency mode will search and try to find every hoard.
        ///&gt;20% of the hoards are unreachable from start.
        ///It will take some seconds to find it.
        ///This mode is still recommended. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_FarmMode_Efficiency_Help {
            get {
                return ResourceManager.GetString("MainWindow_FarmMode_Efficiency_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Safety 的本地化字符串。
        /// </summary>
        internal static string MainWindow_FarmMode_Safety {
            get {
                return ResourceManager.GetString("MainWindow_FarmMode_Safety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Safety mode will NOT search for hoards.
        ///It instantly leaves if the hoard is unreachable. 
        ///Safer and faster runs but you will miss a lot of hoards.
        ///It will take longer overall. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_FarmMode_Safety_Help {
            get {
                return ResourceManager.GetString("MainWindow_FarmMode_Safety_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Config 的本地化字符串。
        /// </summary>
        internal static string MainWindow_OpenConfig {
            get {
                return ResourceManager.GetString("MainWindow_OpenConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Help 的本地化字符串。
        /// </summary>
        internal static string MainWindow_OpenHelp {
            get {
                return ResourceManager.GetString("MainWindow_OpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overall: 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Overall {
            get {
                return ResourceManager.GetString("MainWindow_Overall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progress: {0} / {1} 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Progress {
            get {
                return ResourceManager.GetString("MainWindow_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suffer mode. Unable to calculate the remaining time. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_ProgressNoTime {
            get {
                return ResourceManager.GetString("MainWindow_ProgressNoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Damn it will take ages. Trust me 的本地化字符串。
        /// </summary>
        internal static string MainWindow_ProgressZero {
            get {
                return ResourceManager.GetString("MainWindow_ProgressZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You will need at least {0} of farming to complete the achievement. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_RemainingTime {
            get {
                return ResourceManager.GetString("MainWindow_RemainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You will need at least {0} Days and {1} of farming to complete the achievement. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_RemainingTimeDays {
            get {
                return ResourceManager.GetString("MainWindow_RemainingTimeDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Savegame: 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Savegame {
            get {
                return ResourceManager.GetString("MainWindow_Savegame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Savegame 1 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Savegame_1 {
            get {
                return ResourceManager.GetString("MainWindow_Savegame_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Savegame 2 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Savegame_2 {
            get {
                return ResourceManager.GetString("MainWindow_Savegame_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistics: 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Statistics {
            get {
                return ResourceManager.GetString("MainWindow_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Session 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Statistics_CurrentSession {
            get {
                return ResourceManager.GetString("MainWindow_Statistics_CurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found: {0}   ({1:0.##} %) 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Statistics_Found {
            get {
                return ResourceManager.GetString("MainWindow_Statistics_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runs: {0} 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Statistics_Runs {
            get {
                return ResourceManager.GetString("MainWindow_Statistics_Runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop After: 的本地化字符串。
        /// </summary>
        internal static string MainWindow_StopAfter {
            get {
                return ResourceManager.GetString("MainWindow_StopAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Found Hoards 的本地化字符串。
        /// </summary>
        internal static string MainWindow_StopAfter_Hoards {
            get {
                return ResourceManager.GetString("MainWindow_StopAfter_Hoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minutes 的本地化字符串。
        /// </summary>
        internal static string MainWindow_StopAfter_Minutes {
            get {
                return ResourceManager.GetString("MainWindow_StopAfter_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Runs 的本地化字符串。
        /// </summary>
        internal static string MainWindow_StopAfter_Runs {
            get {
                return ResourceManager.GetString("MainWindow_StopAfter_Runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Support me ♥ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_SupportMe {
            get {
                return ResourceManager.GetString("MainWindow_SupportMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time: {0} 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Time {
            get {
                return ResourceManager.GetString("MainWindow_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time: {0}   (Ø {1}) 的本地化字符串。
        /// </summary>
        internal static string MainWindow_TimeWithAverage {
            get {
                return ResourceManager.GetString("MainWindow_TimeWithAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HoardFarm {0} 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to run: 的本地化字符串。
        /// </summary>
        internal static string MainWindow_UnableToRun {
            get {
                return ResourceManager.GetString("MainWindow_UnableToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This features requires &quot;vnavmesh&quot; to be installed. 的本地化字符串。
        /// </summary>
        internal static string MainWindow_vnavmeshRequired {
            get {
                return ResourceManager.GetString("MainWindow_vnavmeshRequired", resourceCulture);
            }
        }
    }
}
